# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g09mry37GD_dKqrfI530AXa1iq8uqhEm
"""

# =====================================================
# TALLER: SISTEMAS DE RECOMENDACIÓN - CineMax
# Archivo único con los ejercicios solicitados
# =====================================================


# =====================================================
# EJERCICIO 3: Sistema con varios usuarios (uso de ciclos)
# =====================================================

def sistema_varios_usuarios():

    usuarios = {
        "Ana": {"Accion":5, "Comedia":2, "Drama":1, "CienciaFiccion":4, "Terror":1},
        "Luis": {"Accion":1, "Comedia":5, "Drama":2, "CienciaFiccion":1, "Terror":2},
        "Marta": {"Accion":2, "Comedia":1, "Drama":5, "CienciaFiccion":2, "Terror":1},
        "Juan": {"Accion":4, "Comedia":2, "Drama":1, "CienciaFiccion":5, "Terror":1},
        "Sara": {"Accion":1, "Comedia":3, "Drama":2, "CienciaFiccion":1, "Terror":5}
    }

    peliculas = {
        "Accion":"Misión Imposible",
        "Comedia":"Son como niños",
        "Drama":"En busca de la felicidad",
        "CienciaFiccion":"Interestelar",
        "Terror":"El conjuro"
    }

    print("\n===== RECOMENDACIONES PARA TODOS LOS USUARIOS =====\n")

    for usuario, calificaciones in usuarios.items():

        genero_favorito = max(calificaciones, key=calificaciones.get)

        pelicula = peliculas[genero_favorito]

        print("Usuario:", usuario)
        print("Género favorito:", genero_favorito)
        print("Película recomendada:", pelicula)
        print("------------------------------------")


# =====================================================
# EJERCICIO 4: Recomendación tipo Amazon
# =====================================================

def recomendacion_productos():

    productos = {
        "Celular": "Audífonos",
        "Portatil": "Mouse",
        "Televisor": "Barra de sonido",
        "Libro": "Lámpara de lectura",
        "Consola": "Control adicional"
    }

    print("\n===== SISTEMA DE RECOMENDACIÓN DE PRODUCTOS =====\n")

    producto = input("Ingrese el producto comprado: ")

    if producto in productos:

        recomendacion = productos[producto]

        print("\nProducto comprado:", producto)
        print("Producto recomendado:", recomendacion)

    else:

        print("\nNo tenemos una recomendación para ese producto.")


# =====================================================
# EJERCICIO 5: Recomendación por usuarios parecidos
# =====================================================

def recomendacion_por_similitud():

    usuarios = {

        "Ana": {"Pelicula1":True, "Pelicula2":True, "Pelicula3":False, "Pelicula4":False},

        "Juan": {"Pelicula1":True, "Pelicula2":True, "Pelicula3":True, "Pelicula4":False},

        "Luis": {"Pelicula1":False, "Pelicula2":True, "Pelicula3":False, "Pelicula4":True}

    }

    print("\n===== RECOMENDACIÓN POR USUARIOS SIMILARES =====\n")

    def similitud(usuario1, usuario2):

        puntos = 0

        for pelicula in usuario1:

            if usuario1[pelicula] == usuario2[pelicula]:
                puntos += 1

        return puntos


    similitud_juan = similitud(usuarios["Ana"], usuarios["Juan"])
    similitud_luis = similitud(usuarios["Ana"], usuarios["Luis"])

    if similitud_juan > similitud_luis:
        usuario_parecido = "Juan"
    else:
        usuario_parecido = "Luis"

    print("Usuario más parecido a Ana:", usuario_parecido)

    for pelicula, vista in usuarios[usuario_parecido].items():

        if vista and not usuarios["Ana"][pelicula]:

            print("Película recomendada para Ana:", pelicula)


# =====================================================
# MENÚ PRINCIPAL PARA EJECUTAR LOS PROGRAMAS
# =====================================================

def menu():

    while True:

        print("\n========== MENÚ DEL TALLER ==========")
        print("1. Sistema con varios usuarios")
        print("2. Recomendación de productos (Amazon)")
        print("3. Recomendación por usuarios similares")
        print("4. Salir")

        opcion = input("Seleccione una opción: ")

        if opcion == "1":
            sistema_varios_usuarios()

        elif opcion == "2":
            recomendacion_productos()

        elif opcion == "3":
            recomendacion_por_similitud()

        elif opcion == "4":
            print("Saliendo del programa...")
            break

        else:
            print("Opción inválida")


# Ejecutar menú
menu()

